spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566
bible-quiz:
  quiz-generator-endpoint: http://localhost:9000/2015-03-31/functions/function/invocations
logging:
  level:
    org.hibernate.SQL: debug