version: "3.8"

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizdb
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass
    volumes:
      - quiz-volume:/var/lib/mysql
      - ./database/initdb:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - quiz-net

volumes:
  quiz-volume:

networks:
  quiz-net:
